name: Clear cache pipeline (Dispatcher & Akamai)

on:
  workflow_dispatch:
    inputs:
        env:
            required: true
            type: choice
            options:
                - DEV1
                - DEV2
                - TEST
                - INT
                - PrePROD
                - PROD

jobs:
  clear_cache:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  

      - name: Run Python script
        run: python src/main.py ${{inputs.env}}
